// atomic/templates/pagination/index.vue
<template>
  <nav class="documentation-pagination">
    <template v-for="item in paginationItems" :key="item.type">
      <nuxt-link
        v-if="item.page"
        :to="getPageUrl(item.page.category, item.page.slug)"
        :class="['pagination-link', item.type]"
      >
        <span class="pagination-label">{{ item.label }}</span>
        <span class="pagination-title">
          <span v-if="item.type === 'prev'" class="pagination-arrow">←</span>
          {{ item.page.title }}
          <span v-if="item.type === 'next'" class="pagination-arrow">→</span>
        </span>
        <nuc-animation-hexagons />
      </nuxt-link>
      <div v-else class="pagination-placeholder" />
    </template>
  </nav>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'

import { DOC_CATEGORIES, getDocBasePath, parseDocPath } from 'nucleify'

interface PaginationPage {
  category: string
  slug: string
  title: string
}

interface PaginationItem {
  type: 'prev' | 'next'
  label: string
  page: PaginationPage | null
}

const route = useRoute()

const pathInfo = computed(() => parseDocPath(route.path))
const currentLang = computed(() => pathInfo.value?.lang ?? 'en')

const flatPages = computed<PaginationPage[]>(() => {
  const pages: PaginationPage[] = []
  DOC_CATEGORIES.forEach((category) => {
    category.pages.forEach((page) => {
      pages.push({
        category: category.slug,
        slug: page.slug,
        title: page.title,
      })
    })
  })
  return pages
})

const currentIndex = computed(() => {
  if (!pathInfo.value) return -1
  return flatPages.value.findIndex(
    (p) =>
      p.category === pathInfo.value?.category && p.slug === pathInfo.value?.slug
  )
})

const paginationItems = computed<PaginationItem[]>(() => [
  {
    type: 'prev',
    label: 'Previous',
    page:
      currentIndex.value > 0 ? flatPages.value[currentIndex.value - 1] : null,
  },
  {
    type: 'next',
    label: 'Next',
    page:
      currentIndex.value >= 0 && currentIndex.value < flatPages.value.length - 1
        ? flatPages.value[currentIndex.value + 1]
        : null,
  },
])

function getPageUrl(categorySlug: string, pageSlug: string): string {
  const basePath = getDocBasePath(currentLang.value)
  return `${basePath}/${categorySlug}/${pageSlug}`
}
</script>

<style lang="scss">
@import 'index';
</style>

// components/pagination/index.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import React, { useMemo } from 'react'

import {
  DOC_CATEGORIES,
  DocPageInterface,
  getDocBasePath,
  parseDocPath,
} from 'nucleify'

import './_index.scss'

interface PaginationPage {
  category: string
  slug: string
  title: string
}

export function NucDocumentationPagination() {
  const pathname = usePathname()

  const pathInfo = useMemo(() => parseDocPath(pathname || ''), [pathname])
  const currentLang = pathInfo?.lang ?? 'en'

  const flatPages = useMemo<PaginationPage[]>(() => {
    const pages: PaginationPage[] = []
    DOC_CATEGORIES.forEach((category) => {
      category.pages.forEach((page: DocPageInterface) => {
        pages.push({
          category: category.slug,
          slug: page.slug,
          title: page.title,
        })
      })
    })
    return pages
  }, [])

  const currentIndex = useMemo(() => {
    if (!pathInfo) return -1
    return flatPages.findIndex(
      (p) => p.category === pathInfo.category && p.slug === pathInfo.slug
    )
  }, [pathInfo, flatPages])

  const paginationItems = useMemo(() => {
    return [
      {
        type: 'prev',
        label: 'Previous',
        page: currentIndex > 0 ? flatPages[currentIndex - 1] : null,
      },
      {
        type: 'next',
        label: 'Next',
        page:
          currentIndex >= 0 && currentIndex < flatPages.length - 1
            ? flatPages[currentIndex + 1]
            : null,
      },
    ]
  }, [currentIndex, flatPages])

  function getPageUrl(categorySlug: string, pageSlug: string): string {
    const basePath = getDocBasePath(currentLang)
    return `${basePath}/${categorySlug}/${pageSlug}`
  }

  return (
    <nav className="documentation-pagination">
      {paginationItems.map((item) => (
        <React.Fragment key={item.type}>
          {item.page ? (
            <Link
              href={getPageUrl(item.page.category, item.page.slug)}
              className={`pagination-link ${item.type}`}
            >
              <span className="pagination-label">{item.label}</span>
              <span className="pagination-title">
                {item.type === 'prev' && (
                  <span className="pagination-arrow">←</span>
                )}
                {item.page.title}
                {item.type === 'next' && (
                  <span className="pagination-arrow">→</span>
                )}
              </span>
            </Link>
          ) : (
            <div className="pagination-placeholder" />
          )}
        </React.Fragment>
      ))}
    </nav>
  )
}
